version: '3.8'
services:
  dev-database:
    image: 'postgres'
    container_name: 'essentialist-dev-db'
    env_file:
      - .env.development
    ports:
      - 5432:5432
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./sql:/sql
    networks:
      - dev
networks:
  dev:
volumes:
  db_infra: